services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: auth-backend
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: auth-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo
    container_name: auth-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: